/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jumpygrof.github;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashSet;
import javax.swing.JTextField;
import static jumpygrof.github.JumpyGrof.Hafiz;
import static jumpygrof.github.JumpyGrof.Kangaroos;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {

    static int x;
    static int index = 0;
    static int i = 0;
    static int r = 0;
    static int z;
    static int index2 = 1;
    static int countermem = 0;
    static int integerVal = 0;

    GraphVisualization graph = new GraphVisualization();
    static java.util.LinkedList<String> DistinctVertex = new java.util.LinkedList<String>();//used to enter vertexes
    static java.util.LinkedList<String> SourceVertex = new java.util.LinkedList<String>();//to form directed graph
    static java.util.LinkedList<String> DestinationVertex = new java.util.LinkedList<String>();//to form directed graph
    static java.util.LinkedList<Integer> EdgeHeight = new java.util.LinkedList<Integer>();//used to enter edge weight

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        nPoints = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        inPoints = new javax.swing.JTextField();
        panelPoints = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inIDPoint = new javax.swing.JTextField();
        inFood = new javax.swing.JTextField();
        inCapacity = new javax.swing.JTextField();
        inPaths = new javax.swing.JTextField();
        panelConnections = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        inConnected = new javax.swing.JTextField();
        inHeight = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        NoOfKangaroo = new javax.swing.JLabel();
        inKangaroo = new javax.swing.JTextField();
        panelKangaroo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        inStartPoint = new javax.swing.JTextField();
        inPouch = new javax.swing.JTextField();
        inGender = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        inThreshold = new javax.swing.JTextField();
        ok1 = new javax.swing.JButton();
        ok2 = new javax.swing.JButton();
        ok3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        jLabel13.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jTextField1.setText("  JUMPY GROF");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("No of points");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("(2-20)");

        javax.swing.GroupLayout nPointsLayout = new javax.swing.GroupLayout(nPoints);
        nPoints.setLayout(nPointsLayout);
        nPointsLayout.setHorizontalGroup(
            nPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nPointsLayout.createSequentialGroup()
                .addGroup(nPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nPointsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nPointsLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22)))
                .addContainerGap())
        );
        nPointsLayout.setVerticalGroup(
            nPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nPointsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        inPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPointsActionPerformed(evt);
            }
        });

        jLabel1.setText("ID of point");

        jLabel3.setText("No of food");

        jLabel6.setText("Capacity of kangaroos");

        jLabel7.setText("No of paths connected");

        inIDPoint.setEditable(false);

        inFood.setEditable(false);

        inCapacity.setEditable(false);

        inPaths.setEditable(false);
        inPaths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPathsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPointsLayout = new javax.swing.GroupLayout(panelPoints);
        panelPoints.setLayout(panelPointsLayout);
        panelPointsLayout.setHorizontalGroup(
            panelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPointsLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelPointsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inIDPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(panelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPointsLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelPointsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(inFood, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(inCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inPaths, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        panelPointsLayout.setVerticalGroup(
            panelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPointsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inIDPoint)
                    .addComponent(inFood)
                    .addComponent(inCapacity)
                    .addComponent(inPaths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        panelConnections.setPreferredSize(new java.awt.Dimension(300, 90));

        jLabel8.setText("ID of connected point");

        jLabel9.setText("height of obstacles");

        label3.setText("                            ");

        inConnected.setEditable(false);

        inHeight.setEditable(false);
        inHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inHeightActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelConnectionsLayout = new javax.swing.GroupLayout(panelConnections);
        panelConnections.setLayout(panelConnectionsLayout);
        panelConnectionsLayout.setHorizontalGroup(
            panelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConnectionsLayout.createSequentialGroup()
                .addGroup(panelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConnectionsLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(inConnected, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(inHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConnectionsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3)
                            .addGroup(panelConnectionsLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel9)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        panelConnectionsLayout.setVerticalGroup(
            panelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConnectionsLayout.createSequentialGroup()
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConnectionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConnectionsLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConnectionsLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inConnected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        NoOfKangaroo.setText("No of kangaroos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NoOfKangaroo)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NoOfKangaroo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        inKangaroo.setEditable(false);
        inKangaroo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inKangarooActionPerformed(evt);
            }
        });

        jLabel10.setText("Starting point");

        jLabel11.setText("Gender");

        jLabel12.setText("Pouch Capacity");

        inStartPoint.setEditable(false);

        inPouch.setEditable(false);

        inGender.setEditable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Note: For Gender , M is for Male and F is for Female");

        javax.swing.GroupLayout panelKangarooLayout = new javax.swing.GroupLayout(panelKangaroo);
        panelKangaroo.setLayout(panelKangarooLayout);
        panelKangarooLayout.setHorizontalGroup(
            panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKangarooLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKangarooLayout.createSequentialGroup()
                        .addGroup(panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelKangarooLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKangarooLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(inStartPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inGender, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(51, 51, 51)
                        .addGroup(panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKangarooLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(inPouch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)))
                    .addGroup(panelKangarooLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKangarooLayout.setVerticalGroup(
            panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKangarooLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKangarooLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inStartPoint)
                    .addComponent(inPouch)
                    .addComponent(inGender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(6, 6, 6))
        );

        jLabel5.setText("Threshold ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        inThreshold.setEditable(false);
        inThreshold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inThresholdActionPerformed(evt);
            }
        });

        ok1.setText("OK");
        ok1.setEnabled(false);
        ok1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok1MouseClicked(evt);
            }
        });

        ok2.setText("OK");
        ok2.setEnabled(false);
        ok2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok2MouseClicked(evt);
            }
        });

        ok3.setText("OK");
        ok3.setEnabled(false);
        ok3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok3MouseClicked(evt);
            }
        });
        ok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok3ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setVisible(false);
        jLabel14.setText("Error Label");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("PLEASE ENTER WITHOUT SPACE");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setText("A Wild Life Kangaroo Simulator");

        jLabel17.setText("Points                - ");

        jLabel18.setText("Total Capacity   -");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Menu Info");

        jLabel20.setText("Total Kangaroo  -");

        jLabel21.setText("Threshold          -");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(inKangaroo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(459, 459, 459))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panelKangaroo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ok3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panelPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ok1))
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(panelConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ok2)
                                        .addGap(69, 69, 69)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jLabel19))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(inPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel16)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addGap(60, 60, 60)
                        .addComponent(ok1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(inPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(nPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(panelPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(ok2)
                        .addGap(127, 127, 127)
                        .addComponent(ok3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(panelConnections, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inKangaroo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)
                        .addComponent(panelKangaroo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inThreshold, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void inPathsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPathsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inPathsActionPerformed
    private void inPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPointsActionPerformed

        if (inPoints.getText().equals("")) {
            jLabel14.setText("ERROR:YOU DIDNT ENTER ANYTHING IN (POINT(S)) , ENTER AGAIN");
            jLabel14.setVisible(true);
        } else if (checkNumber(inPoints.getText(), inPoints) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER, ENTER AGAIN");
            jLabel14.setVisible(true);
            inPoints.setText("");
        } else if (Integer.parseInt(inPoints.getText()) < 2) {
            jLabel14.setText("ERROR:YOU ENTERED LESS THAN 2 FOR POINTS(MIN IS 20), ENTER AGAIN");
            jLabel14.setVisible(true);
            inPoints.setText("");
        } else if (Integer.parseInt(inPoints.getText()) > 21) {
            jLabel14.setText("ERROR:YOU ENTERED MORE THAN 20 FOR POINTS(MAX IS 20), ENTER AGAIN");
            jLabel14.setVisible(true);
            inPoints.setText("");
        } //    else if(Integer.parseInt(inPoints.getText()) < 0) {
        //        jLabel14.setText("ERROR:YOU ENTERED A NEGATIVE NUMBER, ENTER AGAIN");
        //        jLabel14.setVisible(true);
        //        inPoints.setText("");
        //    }       
        else if (checkNumber(inPoints.getText(), inPoints) == true) {
            String y = inPoints.getText();
            integerVal = Integer.parseInt(y);
            jLabel14.setVisible(false);
            x = Integer.parseInt(y);
            inPoints.setEditable(false);
            inFood.setEditable(true);
            inCapacity.setEditable(true);
            inPaths.setEditable(true);
            ok1.setEnabled(true);
            Hafiz = new Map(x);
            jLabel17.setText("Points                - " + x);
            inIDPoint.setText(index + 1 + "");
        }
    }//GEN-LAST:event_inPointsActionPerformed

    private void ok1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok1MouseClicked

        if (inFood.getText().equals("") || inCapacity.getText().equals("") || inPaths.getText().equals("")) {

            String fooderr = "";
            String Capacityerr = "";
            String Patherr = "";

            if (inFood.getText().equals("")) {
                fooderr = " (FOOD) ";
            }
            if (inCapacity.getText().equals("")) {
                Capacityerr = " (CAPACITY) ";
            }
            if (inPaths.getText().equals("")) {
                Patherr = " (PATH CONNECTED) ";
            }

            jLabel14.setText("ERROR:YOU DIDNT ENTER ANYTHING IN" + fooderr + Capacityerr + Patherr + ", ENTER AGAIN");
            jLabel14.setVisible(true);
        } else if (checkNumber(inFood.getText(), inFood) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (FOOD), ENTER AGAIN)");
            jLabel14.setVisible(true);
            inFood.setText("");
        } else if (checkNumber(inCapacity.getText(), inCapacity) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (CAPACITY), ENTER AGAIN");
            jLabel14.setVisible(true);
            inCapacity.setText("");
        } else if (checkNumber(inPaths.getText(), inPaths) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (PATH CONNECTED), ENTER AGAIN");
            jLabel14.setVisible(true);
            inPaths.setText("");
        } else if (Integer.parseInt(inFood.getText()) <= 0) {
            jLabel14.setText("ERROR:YOU ENTERED LESS THAN 1 NUMBER of Food in (F00D), ENTER AGAIN");
            jLabel14.setVisible(true);
            inFood.setText("");
        } else if (Integer.parseInt(inCapacity.getText()) <= 0) {
            jLabel14.setText("ERROR:YOU ENTERED LESS THAN 1 NUMBER of Kangaroo in (CAPACITY), ENTER AGAIN");
            jLabel14.setVisible(true);
            inCapacity.setText("");
        } else if (Integer.parseInt(inPaths.getText()) < 0) {
            jLabel14.setText("ERROR:YOU ENTERED A NUMBER LESS THAN 0 in (PATH CONNECTED), ENTER AGAIN");
            jLabel14.setVisible(true);
            inPaths.setText("");
        } else if (Integer.parseInt(inPaths.getText()) > x - 1) { // 3  0-2
            jLabel14.setText("ERROR:YOU ENTERED A NUMBER EXCEEDING THE MAX " + (x - 1) + " in (PATH CONNECTED), ENTER AGAIN");
            jLabel14.setVisible(true);
            inPaths.setText("");
        } else if (index < x) {

            if (checkNumber(inIDPoint.getText(), inIDPoint) == true
                    && checkNumber(inFood.getText(), inFood) == true
                    && checkNumber(inCapacity.getText(), inCapacity) == true
                    && checkNumber(inPaths.getText(), inPaths) == true) {

                jLabel14.setVisible(false);

                Hafiz.points.addNode(new Points(Integer.parseInt(inIDPoint.getText()), Integer.parseInt(inFood.getText()),
                        Integer.parseInt(inCapacity.getText()), Integer.parseInt(inPaths.getText())));

                DistinctVertex.add(inIDPoint.getText());

                index++;
                if (index >= x) {
                    ok1.setEnabled(false);
                    inFood.setEditable(false);
                    inCapacity.setEditable(false);
                    inPaths.setEditable(false);
                    jLabel18.setText("Total Capacity   - " + JumpyGrof.Hafiz.getmaxkangmap());
                    iterate();

                } else {
                    inIDPoint.setText(index + 1 + "");
                    inFood.setText("");
                    inCapacity.setText("");
                    inPaths.setText("");
                }

            } else {
                inFood.setText("");
                inCapacity.setText("");
                inPaths.setText("");

            }
        }
    }//GEN-LAST:event_ok1MouseClicked
    public void iterate() {

        if (i < Hafiz.numberofpoints) {
            if ((Hafiz.points.atindex(i).getnumroute() != 0)) {

                label3.setText("Point " + Hafiz.points.atindex(i).getpointID() + " is connected to");
                inConnected.setEditable(true);
                inHeight.setEditable(true);
                ok2.setEnabled(true);

            } else {
                i++;
                iterate();
            }
        } else {

            inConnected.setEditable(false);
            inHeight.setEditable(false);
            ok2.setEnabled(false);
            inKangaroo.setEditable(true);

        }

    }

    int routemem[];
    int heightmem[];
    int dupp[];


    private void ok2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok2MouseClicked

        if (inConnected.getText().equals("") || inHeight.getText().equals("")) {

            String connectederr = "";
            String heighterr = "";

            if (inConnected.getText().equals("")) {
                connectederr = " (CONNECTED) ";
            }
            if (inHeight.getText().equals("")) {
                heighterr = " (HEIGHT) ";
            }

            jLabel14.setText("ERROR:YOU DIDNT ENTER ANYTHING IN" + connectederr + heighterr + ", EENTER AGAIN");
            jLabel14.setVisible(true);
        } else if (checkNumber(inConnected.getText(), inConnected) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (CONNECTED), ENTER AGAIN)");
            jLabel14.setVisible(true);
            inConnected.setText("");
        } else if (checkNumber(inHeight.getText(), inHeight) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (HEIGHT), ENTER AGAIN)");
            jLabel14.setVisible(true);
            inHeight.setText("");
        } else if (inConnected.getText().equals(Hafiz.points.atindex(i).getpointID())) {
            jLabel14.setText("ERROR:YOU CANNOT DIRECT TO THE SOURCE, ENTER AGAIN");
            jLabel14.setVisible(true);
            inConnected.setText("");
        } else if (Integer.parseInt(inHeight.getText()) < 0) {
            jLabel14.setText("ERROR:YOU ENTERED A NEGATIVE NUMBER in (HEIGHT), ENTER AGAIN");
            jLabel14.setVisible(true);
            inHeight.setText("");
        } else if (Integer.parseInt(inConnected.getText()) < 0) {
            jLabel14.setText("ERROR:YOU ENTERED A NEGATIVE NUMBER in (CONNECTED), ENTER AGAIN");
            jLabel14.setVisible(true);
            inConnected.setText("");
        } else if (Integer.parseInt(inConnected.getText()) == Hafiz.points.atindex(i).getpointID()) {
            jLabel14.setText("ERROR:YOU ENTERED THE SAME NUMBER FOR THE ID in (CONNECTED), ENTER AGAIN");
            jLabel14.setVisible(true);
            inConnected.setText("");
        } else if (Integer.parseInt(inConnected.getText()) > Hafiz.numberofpoints) {
            jLabel14.setText("ERROR:YOU ENTERED AN INVALID POINT, ENTER AGAIN");
            jLabel14.setVisible(true);
            inConnected.setText("");
        } else if (checkNumber(inConnected.getText(), inConnected) == true && checkNumber(inHeight.getText(), inHeight) == true) {
            if (r == 0) {
                routemem = new int[Hafiz.points.atindex(i).getnumroute()];
                heightmem = new int[Hafiz.points.atindex(i).getnumroute()];
                dupp = new int[Hafiz.points.atindex(i).getnumroute()];
                countermem = 0;
            }

            if (r < Hafiz.points.atindex(i).getnumroute()) {
                if (checkNumber(inConnected.getText(), inConnected) == true && checkNumber(inHeight.getText(), inHeight) == true) {
                    jLabel14.setVisible(false);
                    boolean duplicate = false;
                    int connectedID = Integer.parseInt(inConnected.getText());
                    int tempheight = Integer.parseInt(inHeight.getText());

                    for (int p = 0; p < dupp.length; p++) {
                        if (dupp[p] == connectedID) {
                            duplicate = true;
                            jLabel14.setText("ERROR:WARNING A DUPLICATE ROUTE IS ENTERED,PLEASE ENTER A NEW ROUTE");
                            jLabel14.setVisible(true);
                            inConnected.setText("");
                            inHeight.setText("");
                        }
                    }

                    for (int t = 0; t < Hafiz.numberofpoints; t++) {

                        if (Hafiz.points.atindex(t).getpointID() == connectedID && duplicate == false) { //CHECK THIS ONE AGAIN    
                            jLabel14.setVisible(false);
                            dupp[countermem] = connectedID;
                            routemem[countermem] = t;
                            heightmem[countermem] = tempheight;
                            countermem++;

                            //Hafiz.points.atindex(i).addroute(new Route(Hafiz.points.atindex(t), tempheight));// tambah jalan
                            inConnected.setText("");
                            inHeight.setText("");
                            r++;

                            SourceVertex.add(Integer.toString(Hafiz.points.atindex(i).getpointID()));
                            DestinationVertex.add(Integer.toString(connectedID));
                            EdgeHeight.add(tempheight);

                        }
                    }
                } else {
                    jLabel14.setVisible(false);
                    inConnected.setText("");
                    inHeight.setText("");
                }
            }

            if (r == Hafiz.points.atindex(i).getnumroute()) {

                for (int y = 0; y < routemem.length; y++) {
                    Hafiz.points.atindex(i).addroute(new Route(Hafiz.points.atindex(routemem[y]), heightmem[y]));

                }
                r++;

            }
            if (r > Hafiz.points.atindex(i).getnumroute()) {
                r = 0;
                i++;
                inConnected.setText("");
                inHeight.setText("");
                iterate();
            }
        }
    }//GEN-LAST:event_ok2MouseClicked


    private void ok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ok3ActionPerformed

    private void inHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inHeightActionPerformed

    private void inKangarooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inKangarooActionPerformed

        if (inKangaroo.getText().equals("")) {
            jLabel14.setText("ERROR:YOU DIDNT ENTER ANYTHING IN (KANGAROO(S)) , ENTER AGAIN");
            jLabel14.setVisible(true);
        } else if (checkNumber(inKangaroo.getText(), inKangaroo) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER IN (KANGAROO(S)), ENTER AGAIN");
            jLabel14.setVisible(true);
            inKangaroo.setText("");
        } else if (Integer.parseInt(inKangaroo.getText()) <= 0) {
            jLabel14.setText("ERROR:YOU ENTERED A Number less than or equal to 0 in (KANGAROO(S)), ENTER AGAIN");
            jLabel14.setVisible(true);
            inKangaroo.setText("");
        } else if (Integer.parseInt(inKangaroo.getText()) > JumpyGrof.Hafiz.getmaxkangmap()) {
            jLabel14.setText("ERROR:THE AMOUNT EXCEED THE CAPACITY OF THE MAP " + JumpyGrof.Hafiz.getmaxkangmap() + ", ENTER AGAIN");
            jLabel14.setVisible(true);
            inKangaroo.setText("");
        } else if (checkNumber(inKangaroo.getText(), inKangaroo) == true) {
            String g = inKangaroo.getText();
            jLabel14.setVisible(false);
            z = Integer.parseInt(g);
            jLabel20.setText("Total Kangaroo  - " + z);
            inKangaroo.setEditable(false);
            inStartPoint.setEditable(true);
            inGender.setEditable(true);
            inPouch.setEditable(true);
            ok3.setEnabled(true);

        }
    }//GEN-LAST:event_inKangarooActionPerformed

    private void ok3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok3MouseClicked

        if (checkGender(inGender.getText(), inGender) == false) {
            jLabel14.setText("ERROR:YOU ENTERED NEITHER OF WHICH,F FOR FEMALE M FOR MALE Value in (GENDER), ENTER AGAIN)");
            jLabel14.setVisible(true);
            inGender.setText("");
        } //        else if(!inGender.getText().equals("F") || !inGender.getText().equals("f") || !inGender.getText().equals("M") || !inGender.getText().equals("m")) {
        //            jLabel14.setText("ERROR:YOU ENTERED A NEITHER F OR M Value in (GENDER), ENTER AGAIN)");
        //            jLabel14.setVisible(true);
        //            inGender.setText("");
        //        }
        else if (inStartPoint.getText().equals("") || inGender.getText().equals("") || inPouch.getText().equals("")) {

            String startpointerr = "";
            String gendererr = "";
            String poucherr = "";

            if (inStartPoint.getText().equals("")) {
                startpointerr = " (START POINT) ";
            }
            if (inGender.getText().equals("")) {
                gendererr = " (GENDER) ";
            }
            if (inPouch.getText().equals("")) {
                poucherr = " (POUCH) ";
            }

            jLabel14.setText("ERROR:YOU DIDNT ENTER ANYTHING IN" + startpointerr + gendererr + poucherr + ", ENTER AGAIN");
            jLabel14.setVisible(true);
        } else if (checkNumber(inStartPoint.getText(), inStartPoint) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (START POINT), ENTER AGAIN)");
            jLabel14.setVisible(true);
            inStartPoint.setText("");
        } else if (checkNumber(inPouch.getText(), inPouch) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER Value in (POUCH), ENTER AGAIN)");
            jLabel14.setVisible(true);
            inPouch.setText("");
        } else if (Integer.parseInt(inStartPoint.getText()) < 0) {
            jLabel14.setText("ERROR:YOU ENTERED A NEGATIVE NUMBER in (START POINT), ENTER AGAIN");
            jLabel14.setVisible(true);
            inStartPoint.setText("");
        } else if (Integer.parseInt(inPouch.getText()) < 0) {
            jLabel14.setText("ERROR:YOU ENTERED A NEGATIVE NUMBER in (POUCH), ENTER AGAIN");
            jLabel14.setVisible(true);
            inPouch.setText("");
        } else if (index2 <= z) {
            if (checkNumber(inStartPoint.getText(), inStartPoint) == true
                    && checkNumber(inPouch.getText(), inPouch) == true
                    && checkGender(inGender.getText(), inGender) == true) {
                char c = inGender.getText().charAt(0);
                char c1 = Character.toUpperCase(c);
                Kangaroos.addNode(new Kangaroo(Integer.parseInt(inStartPoint.getText()), c1, Integer.parseInt(inPouch.getText())));

                inStartPoint.setText("");
                inGender.setText("");
                inPouch.setText("");
                index2++;
                if (index2 > z) {
                    ok3.setEnabled(false);
                    inStartPoint.setEditable(false);
                    inGender.setEditable(false);
                    inPouch.setEditable(false);
                    inThreshold.setEditable(true);
                }
            } else {
                inStartPoint.setText("");
                inGender.setText("");
                inPouch.setText("");
            }
        }
    }//GEN-LAST:event_ok3MouseClicked


    private void inThresholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inThresholdActionPerformed

        if (inThreshold.getText().equals("")) {
            jLabel14.setText("ERROR:YOU DIDNT ENTER ANYTHING IN (THRESHOLD) , ENTER AGAIN");
            jLabel14.setVisible(true);
        } else if (checkNumber(inThreshold.getText(), inThreshold) == false) {
            jLabel14.setText("ERROR:YOU ENTERED A NON INTEGER IN (THRESHOLD), ENTER AGAIN");
            jLabel14.setVisible(true);
            inThreshold.setText("");
        } //        else if (Integer.parseInt(inThreshold.getText()) < 0) {
        //            jLabel14.setText("ERROR:YOU ENTERED A NEGATIVE NUMBER in (THRESHOLD), ENTER AGAIN");
        //            jLabel14.setVisible(true);
        //            inThreshold.setText("");
        //        }
        else if (Integer.parseInt(inThreshold.getText()) < 1) {
            jLabel14.setText("ERROR:YOU ENTERED A NUMBER LESS THAN 1 in (THRESHOLD), ENTER AGAIN");
            jLabel14.setVisible(true);
            inThreshold.setText("");
        } else if (checkNumber(inThreshold.getText(), inThreshold) == true) {
            String c = inThreshold.getText();
            int threshold = Integer.parseInt(c);
            inThreshold.setEditable(false);
            jLabel21.setText("Threshold          - " + threshold);
            Points.colony = threshold;
            output();
            //System.exit(0);
        }
    }//GEN-LAST:event_inThresholdActionPerformed

    public boolean checkNumber(String a, JTextField b) {
        try {
            int x = Integer.parseInt(a);
        } catch (NumberFormatException e) {
            b.setText("");
            return false;
        }
        return true;
    }

    public boolean checkGender(String a, JTextField b) {

        char x = a.charAt(0);
        if (x == 'M' || x == 'F' || x == 'm' || x == 'f') {
            return true;
        } else {
            b.setText("");
            return false;
        }
    }

    public void output() {

        graph.Visualize_Directed_Graph(DistinctVertex, SourceVertex, DestinationVertex, EdgeHeight);

        System.out.println("_____________________________________________________________");
        System.out.println("List of route taken by the Kangaroo(s)");
        Hafiz.tick();

        //
        int counter = 0;
        for (int i = 0; i < Kangaroos.length(); i++) { //kira bilangan kangaroo yang ada dalam colony
            if (Kangaroos.atindex(i).isincolony() == false) {
                //  System.out.println(JumpyGrof.Kangaroos.atindex(i).toString());
                counter++;
            }
        }
        for (int i = 0; i < Hafiz.points.length(); i++) {
            //   System.out.println("Food at point " + JumpyGrof.Hafiz.points.atindex(i).getpointID() + ": " + JumpyGrof.Hafiz.points.atindex(i).getfood());
        }

        //  System.out.println("Number of colony formed: " + Points.numberofcolony);
        System.out.println();
        System.out.println();
        //List of Kangaroos that was not able to colonized
        System.out.println("List of Kangaroos that was not able to colonized");
        System.out.println("Number of Remaining Kangaroos: " + counter);
        for (int i = 0; i < Kangaroos.length(); i++) {
            if (Kangaroos.atindex(i).isincolony() == false) {
                System.out.println(Kangaroos.atindex(i).toString());
            }
        }
        System.out.println();
        System.out.println();
        counter = 0;
        //

        //
        System.out.println("LIST OF FOOD LEFT (DEBUGGING)");
        for (int i = 0; i < Hafiz.points.length(); i++) {
            System.out.println("Food at point " + Hafiz.points.atindex(i).getpointID() + ": " + Hafiz.points.atindex(i).getfood());
        }
        System.out.println();
        //

        //List of Kangaroos that are able to colonized
        System.out.println("List of Kangaroos that are able to colonized");
        for (int i = 0; i < Kangaroos.length(); i++) {
            if (Kangaroos.atindex(i).isincolony() == true) {
                counter++;
            }
        }
        System.out.println("Number of colony formed: " + Points.numberofcolony);
        System.out.println("Number of Kangaroos that are colonized: " + counter);
        for (int i = 0; i < Hafiz.points.length(); i++) {
            if (Hafiz.points.atindex(i).iscolonized() == true) {
                System.out.println("Colony at point " + Hafiz.points.atindex(i).getpointID());
                for (int j = 0; j < Kangaroos.length(); j++) {
                    if (Kangaroos.atindex(j).getpointID() == Hafiz.points.atindex(i).getpointID()) {
                        System.out.println(Kangaroos.atindex(j).toString());
                    }
                }
            }
        }
        System.out.println("________________________________________________________________________________________");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NoOfKangaroo;
    private javax.swing.JTextField inCapacity;
    private javax.swing.JTextField inConnected;
    private javax.swing.JTextField inFood;
    private javax.swing.JTextField inGender;
    private javax.swing.JTextField inHeight;
    private javax.swing.JTextField inIDPoint;
    private javax.swing.JTextField inKangaroo;
    private javax.swing.JTextField inPaths;
    private javax.swing.JTextField inPoints;
    private javax.swing.JTextField inPouch;
    private javax.swing.JTextField inStartPoint;
    private javax.swing.JTextField inThreshold;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label3;
    private javax.swing.JPanel nPoints;
    private javax.swing.JButton ok1;
    private javax.swing.JButton ok2;
    private javax.swing.JButton ok3;
    private javax.swing.JPanel panelConnections;
    private javax.swing.JPanel panelKangaroo;
    private javax.swing.JPanel panelPoints;
    // End of variables declaration//GEN-END:variables
}
